services:
  postgres:
    image: postgres:14.22
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:26.3
    container_name: clickhouse_db
    environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: password
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8123/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  jupyter:
    build:
      context: .
    container_name: jupyter_spark
    ports:
      - "8888:8888"
      - "9001:9001"
    volumes:
      - ./notebooks:/app/notebooks
    environment:
      PYSPARK_DRIVER_PYTHON: jupyter
      JUPYTER_ENABLE_LAB: yes
      PYSPARK_DRIVER_PYTHON_OPTS: "lab --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --no-browser"
    command:
      pyspark
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  spark:
    build:
      context: .
    container_name: spark_ingest
    user: root # Required to install jars or write to certain volumes
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    volumes:
      - ./spark:/app
    entrypoint: /app/entrypoint.sh
